clear; clc;
load("ik_dataset_branchaware_prepared.mat");
layers = [featureInputLayer(13) fullyConnectedLayer(128) reluLayer fullyConnectedLayer(256) reluLayer fullyConnectedLayer(256) reluLayer fullyConnectedLayer(128) reluLayer fullyConnectedLayer(64) reluLayer fullyConnectedLayer(6) regressionLayer];
options = trainingOptions("adam", ...
    "MaxEpochs",100, ...
    "MiniBatchSize",256, ...
    "InitialLearnRate",0.001, ...
    "Shuffle","every-epoch", ...
    "ValidationData",{XValNorm,YValNorm}, ...
    "ValidationFrequency",50, ...
    "Plots","training-progress", ...
    "Verbose",true);
net=trainNetwork(XTrainNorm,YTrainNorm,layers,options);
save("ik_branchaware_network.mat","net","XMean","XStd","YMean","YStd");